name: Tests CI

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make libgtest-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j2

    - name: Run tests
      run: ./build/run_test

